<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="#">
				<em class="fa fa-home"></em>
			</a></li>
			<li class="active"><?php echo $this->controlador ?> / <?php echo $this->miga ?></li>
		</ol>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><?php echo $this->controlador ?></h1>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading"><?php echo $this->miga ?></div>
		<div class="panel-body btn-margins">
			<div class="col-md-12">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
					<div id="alert"></div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Documento: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="documento" class="form-control integer required" value="<?php if(isset($this->dato)){ echo $this->dato->getDocumento();} ?>" />
		                </div>
		           	</div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Nombre: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="nombre" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
		                </div>
		           	</div>
		           	<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Apellido: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="apellido" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getApellido();} ?>" />
		                </div>
		           	</div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Correo: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="correo" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getCorreo();} ?>" />
		                </div>
		           	</div>
		           	<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Tel&eacute;fono: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="telefono" class="form-control integer required" value="<?php if(isset($this->dato)){ echo $this->dato->getTelefono();} ?>" />
		                </div>
		           	</div>
		           	<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label required" >Sexo: <span class="span">*</span></label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
							<select name="sexo" class="form-control required">
		                        <option value="">Seleccione... </option>
		                        <option <?php if(isset($this->dato) && $this->dato->getSexo() == 1) echo "selected" ?> value="1">Masculino</option>
		                        <option <?php if(isset($this->dato) && $this->dato->getSexo() == 2) echo "selected" ?> value="2">Femenino</option>
		                    </select>
						</div>
					</div>
					<p class="text-right comentario">
						Los campos marcados con <span class="span">*</span> son obligatorios.
					</p>
					<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
					<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>
				</form>
			</div>
		</div>
	</div>
</div>
</div>