<div class="panel panel-primary">
	  <div class="panel-heading">
			<h3 class="panel-title">Listado</h3>
	  </div>
	  <div class="panel-body">
				<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
					<thead>
						<tr>
							<th>Placa</th>
							<th>Fecha</th>
							<th>Tipo</th>
							<th>Frecuencia</th>
							<th class="text-center no-sort" >Acción</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->datos as $key => $dato) { ?>
							<tr>
								<td><?php echo $dato->getVehiculo()->getPlaca(); ?></td>
								<td><?php echo $dato->getFecha()->format('d/m/Y'); ?></td>
								<td><?php echo $dato->getTipo()==1?"Preventivo":"Correctivo"; ?></td>
								<td><?php echo $dato->getFrecuencia()->getDescripcion(); ?></td>
								<td class="text-center">
									<a data-id="<?php echo $dato->getId(); ?>" title="Detalles" class="this-vermas" href="#"><i class="fa fa-search-plus"></i></a>
									<a title="Actualizar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>actualizar/<?php echo $dato->getId(); ?>/"><i class="fa fa-pencil-square-o"></i></a>
									
									<a target="_blank" title="Ficha Técnica" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>fichaVehiculo/<?php echo $dato->getId(); ?>/"><i class="fa fa-file-text"></i></a>
									
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
				<a href="<?php echo BASE_URL.$this->_presentRequest->getControlador()."/agregar/" ?>" class="btn btn-primary">Agregar</a>
	  </div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('.this-vermas').click(function(event) {
	        event.preventDefault();
	        motrarGet($(this),BASE.url+'<?php echo $this->_presentRequest->getControlador(); ?>/get/');
	    });
	});
</script>