<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="#">
				<em class="fa fa-home"></em>
			</a></li>
			<li class="active">Tipo Mensaje / <?php echo $this->miga ?></li>
		</ol>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Tipo Mensaje</h1>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading"><?php echo $this->miga ?></div>
		<div class="panel-body btn-margins">
			<div class="col-md-12">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
					<div id="alert"></div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Nombre: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="nombre" class="form-control required" value="<?php if(isset($this->dato)){ echo $this->dato->getNombre();} ?>" />
		                </div>
		           	</div>
		           	<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Valor: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="valor" class="form-control integer required" value="<?php if(isset($this->dato)){ echo $this->dato->getValor();} ?>" />
		                </div>
		           	</div>
		           	<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Estado: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <select name="estado" class="form-control required">
			                	<option value="">Seleccione...</option>
			                	<option value="1" <?php if(isset($this->dato) && $this->dato->getEstado() == "1") echo "selected" ?> >ACTIVO</option>
			                	<option value="0" <?php if(isset($this->dato) && $this->dato->getEstado() == "0") echo "selected" ?> >INACTIVO</option>
			                </select>
		                </div>
		           	</div>
					<p class="text-right comentario">
						Los campos marcados con <span class="span">*</span> son obligatorios.
					</p>
					<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
					<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>
				</form>
			</div>
		</div>
	</div>
</div>
</div>