<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="#">
				<em class="fa fa-home"></em>
			</a></li>
			<li class="active">Mensaje Campaña / <?php echo $this->miga ?></li>
		</ol>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Mensaje Campaña</h1>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading"><?php echo $this->miga ?></div>
		<div class="panel-body btn-margins">
			<div class="col-md-12">
				<form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
					<div id="alert"></div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Telefono: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <input name="telefono" class="form-control integer required" value="<?php if(isset($this->dato)){ echo $this->dato->getTelefono();} ?>" />
		                </div>
		           	</div>
					<div class="form-group">
		                <label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Mensaje: <span class="span">*</span></label>
		                <div class="col-xs-12 col-sm-9 col-lg-9">
			                <textarea name="mensaje" class="form-control required" maxlength="300" rows = "4"><?php if(isset($this->dato)){ echo $this->dato->getMensaje();} ?></textarea>
		                </div>
		           	</div>
		           	<div class="form-group">
						<label class="col-xs-12 col-sm-3 col-lg-3 control-label" >Fecha Envio: <span class="span">*</span></label>
						<div class="col-xs-12 col-sm-9 col-lg-9">
						<input name="fechaEnvio" class="form-control datepicker required" data-date-format="dd/mm/yyyy" placeholder=" dd/mm/aaaa" value="<?php if(isset($this->dato)){ if($this->dato->getFechaCampa()) { echo $this->dato->getFechaCampa()->format('d/m/Y');} } ?>" />
						</div>
					</div>
					<p class="text-right comentario">
						Los campos marcados con <span class="span">*</span> son obligatorios.
					</p>
					<button type="submit" class="btn btn-primary" ><?php echo ucwords($this->_presentRequest->getMetodo()); ?> </button> 
					<a class="btn btn-primary" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>">Listado</a>
				</form>
			</div>
		</div>
	</div>
</div>
</div>