<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="#">
				<em class="fa fa-home"></em>
			</a></li>
			<li class="active"><?php echo $this->controlador ?></li>
		</ol>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><?php echo $this->controlador ?></h1>
		</div>
	</div>
	<div class="panel panel-default">
	<div class="panel-heading">Listado</div>
		<div class="panel-body btn-margins">
			<div class="col-md-12">
				<table class="table table-striped table-bordered table-hover" id="dataTablesAdvanced">
					<thead>
						<tr>
							<th>ID</th>
							<th>Nombre</th>
							<th>Usuario</th>
							<th>Saldo</th>
							<th>Tipo</th>
							<th class="text-center no-sort" >Acción</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->datos as $key => $dato) { ?>
						<tr>
							<td><?php echo $dato->getId(); ?></td>
							<td><?php echo $dato->getNombre(); ?></td>
							<td><?php echo $dato->getUsuario(); ?></td>
							<td><?php echo $dato->getSaldo(); ?></td>
							<td><?php echo $dato->getTipoUsuario()->getNombre(); ?></td>
							<td class="text-center">
								<a title="Actualizar" href="<?php echo BASE_URL.$this->_presentRequest->getControlador().'/'; ?>actualizar/<?php echo $dato->getId(); ?>/"><i class="fa fa-pencil-square-o"></i></a>
							</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
				<a href="<?php echo BASE_URL.$this->_presentRequest->getControlador()."/agregar/" ?>" class="btn btn-primary">Agregar</a> 
			</div>
		</div>
	</div>
</div>
</div>